// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mirosnicenco_Eugenia_Proiect.Data;

#nullable disable

namespace Mirosnicenco_Eugenia_Proiect.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260111203943_ActualizareBD")]
    partial class ActualizareBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<decimal>("AvgIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.EnergyProvider", b =>
                {
                    b.Property<int>("EnergyProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnergyProviderId"));

                    b.Property<double>("GreenEnergyShare")
                        .HasColumnType("float");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnergyProviderId");

                    b.ToTable("EnergyProvider");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.EnergyUsage", b =>
                {
                    b.Property<int>("EnergyUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnergyUsageId"));

                    b.Property<double>("AvgMonthlyConsumption")
                        .HasColumnType("float");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("EnergyUsageId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("EnergyUsage");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.Household", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseholdId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("HouseholdSize")
                        .HasColumnType("int");

                    b.Property<string>("IncomeLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrbanRural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HouseholdId");

                    b.HasIndex("CountryId");

                    b.ToTable("Household");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.RenewableSystem", b =>
                {
                    b.Property<int>("RenewableSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenewableSystemId"));

                    b.Property<double>("CapacityKW")
                        .HasColumnType("float");

                    b.Property<int>("EnergyProviderId")
                        .HasColumnType("int");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<int>("InstalationYear")
                        .HasColumnType("int");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RenewableSystemId");

                    b.HasIndex("EnergyProviderId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("RenewableSystem");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.EnergyUsage", b =>
                {
                    b.HasOne("Mirosnicenco_Eugenia_Proiect.Models.Household", "Household")
                        .WithMany("EnergyUsages")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.Household", b =>
                {
                    b.HasOne("Mirosnicenco_Eugenia_Proiect.Models.Country", "Country")
                        .WithMany("Households")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.RenewableSystem", b =>
                {
                    b.HasOne("Mirosnicenco_Eugenia_Proiect.Models.EnergyProvider", "EnergyProvider")
                        .WithMany("RenewableSystems")
                        .HasForeignKey("EnergyProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mirosnicenco_Eugenia_Proiect.Models.Household", "Household")
                        .WithMany("RenewableSystems")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergyProvider");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.Country", b =>
                {
                    b.Navigation("Households");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.EnergyProvider", b =>
                {
                    b.Navigation("RenewableSystems");
                });

            modelBuilder.Entity("Mirosnicenco_Eugenia_Proiect.Models.Household", b =>
                {
                    b.Navigation("EnergyUsages");

                    b.Navigation("RenewableSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
