// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class AvgMontlyConsumptionPredictionModel
{
    /// <summary>
    /// model input class for AvgMontlyConsumptionPredictionModel.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(2)]
        [ColumnName(@"Country")]
        public string Country { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"Monthly_Usage_kWh")]
        public float Monthly_Usage_kWh { get; set; }

        [LoadColumn(6)]
        [ColumnName(@"Household_Size")]
        public float Household_Size { get; set; }

        [LoadColumn(7)]
        [ColumnName(@"Income_Level")]
        public string Income_Level { get; set; }

        [LoadColumn(8)]
        [ColumnName(@"Urban_Rural")]
        public string Urban_Rural { get; set; }

        [LoadColumn(9)]
        [ColumnName(@"Adoption_Year")]
        public float Adoption_Year { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for AvgMontlyConsumptionPredictionModel.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"Country")]
        public float[] Country { get; set; }

        [ColumnName(@"Monthly_Usage_kWh")]
        public float Monthly_Usage_kWh { get; set; }

        [ColumnName(@"Household_Size")]
        public float Household_Size { get; set; }

        [ColumnName(@"Income_Level")]
        public float[] Income_Level { get; set; }

        [ColumnName(@"Urban_Rural")]
        public float[] Urban_Rural { get; set; }

        [ColumnName(@"Adoption_Year")]
        public float Adoption_Year { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("AvgMontlyConsumptionPredictionModel.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }
}
